# Generated by Django 5.1.1 on 2024-09-29 03:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('starter', models.CharField(max_length=100)),
                ('main_course', models.CharField(max_length=100)),
                ('dessert', models.CharField(max_length=100)),                
            ],
        ),
    ]
